---
name: Pull request
on:
  push:
    branches:
      - main
  pull_request:
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compliance test suite
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Run black code style checker
        uses: psf/black@stable

      - name: Install compliance test suite dependencies
        run: pip install -r requirements.txt

      - name: Install mypy type checker
        run: pip install mypy boto3-stubs botocore-stubs types-requests

      - name: Run mypy type checker
        run: mypy compliance

  compliance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compliance test suite
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Checkout active storage server
        uses: actions/checkout@v3
        with:
          repository: stackhpc/s3-active-storage-rs
          path: s3-active-storage-rs

      - name: Build
        run: make build
        working-directory: s3-active-storage-rs

      - name: Install compliance test suite dependencies
        run: pip install -r requirements.txt

      - name: Configure compliance test suite
        run: |
          echo 'PROXY_URL = "http://localhost:8080"' >> compliance/config.py

      - name: Start minio object storage
        run: scripts/minio-start
        working-directory: s3-active-storage-rs

      - name: Wait for minio object storage to start
        run: |
          until curl -if http://localhost:9001; do
            sleep 1;
          done

      - name: Run active storage container
        run: make run
        working-directory: s3-active-storage-rs

      - name: Wait for active storage server to start
        run: |
          until curl -if http://localhost:8080/.well-known/s3-active-storage-schema; do
            sleep 1;
          done

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Run compliance test suite
        run: pytest -s > artifacts/pytest.log

      - name: Get active storage logs
        run: docker logs s3-active-storage > artifacts/s3-active-storage.log
        if: always()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compliance-test
          path: artifacts
        if: always()

      - name: Stop minio object storage
        run: scripts/minio-stop
        working-directory: s3-active-storage-rs
        if: always()

      - name: Stop active storage container
        run: make stop
        working-directory: s3-active-storage-rs
        if: always()
