---
name: Pull request
on:
  push:
    branches:
      - main
  pull_request:
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compliance test suite
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Run black code style checker
        uses: psf/black@stable

      - name: Install compliance test suite dependencies
        run: pip install -r requirements.txt

      - name: Run mypy type checker
        run: mypy compliance

      - name: Run flake8
        run: flake8
  compliance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout compliance test suite
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Checkout Reductionist server
        uses: actions/checkout@v3
        with:
          repository: stackhpc/reductionist-rs
          path: reductionist-rs

      - name: Build
        run: make build
        working-directory: reductionist-rs

      - name: Install compliance test suite dependencies
        run: pip install -r requirements.txt

      - name: Configure compliance test suite
        run: |
          echo 'PROXY_URL = "http://localhost:8080"' >> compliance/config.py

      - name: Start minio object storage
        run: scripts/minio-start
        working-directory: reductionist-rs

      - name: Wait for minio object storage to start
        run: |
          until curl -if http://localhost:9001; do
            sleep 1;
          done

      - name: Run Reductionist container
        run: make run
        working-directory: reductionist-rs

      - name: Wait for Reductionist server to start
        run: |
          until curl -if http://localhost:8080/.well-known/reductionist-schema; do
            sleep 1;
          done

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Run compliance test suite
        run: pytest -s > artifacts/pytest.log

      - name: Get Reductionist logs
        run: docker logs reductionist > artifacts/reductionist.log
        if: always()

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compliance-test
          path: artifacts
        if: always()

      - name: Stop minio object storage
        run: scripts/minio-stop
        working-directory: reductionist-rs
        if: always()

      - name: Stop Reductionist container
        run: make stop
        working-directory: reductionist-rs
        if: always()
